### ISSUE TITLE
Coveralls

### ISSUE THREAD

**Issue by a8568730** [i3thuan5/Taiwanese-serif-to-Unicode#1]
我是用coveralls。

我有振動兩份檔案：
[.travis.yml](https://github.com/i3thuan5/su5lui3-hun1kip4-hok8bu7/blob/master/.travis.yml)
```
dist: xenial
language: python
python:
- '3.5'
env:
  matrix:
  - TOX_ENV=testAll
  - TOX_ENV=BDD
  - TOX_ENV=flake8
branches:
  only:
  - master
services:
- rabbitmq
install:
- pip install tox
- pip install coveralls
- sudo apt-get install wkhtmltopdf -y xvfb
script:
- tox -e $TOX_ENV
after_success:
- coverage report
- coveralls
```

.tox.ini
```
[testenv:BDD]
deps =
    coverage -r requirements.txt
commands =
    coverage run manage.py behave --simple
```
